{
 "title": "single selected stock data real time analysis",
 "description": "his query uses a window function with FIRST_VALUE to get the first open value within a rolling window of the current and previous row, grouped by symbol.",
 "time": { "from": "2024-09-03T04:00:00.000Z", "to": "2025-01-28T19:59:00.000Z" },
 "templating": {
  "list": [
   {
    "name": "symbols_list",
    "query": "select distinct(symbol) from stock_data"
   },
   {
    "name": "custom_average_interval_minutes",
    "query": "15"
   },
   {
    "name": "sentiment_score_definition",
    "query": "SELECT\n    content->>'sentiment_score_definition' AS Sentiment_Score_Definition\nFROM\n    sentiment_data\nORDER BY\n    uploaded_at DESC\nLIMIT 1;\n"
   },
   {
    "name": "relevance_score_definition",
    "query": "SELECT\n    content->>'relevance_score_definition' AS relevance_score_definition\nFROM\n    sentiment_data\nORDER BY\n    uploaded_at DESC\nLIMIT 1;\n"
   }
  ]
 },
 "panels": [
  {
   "title": "Open Stock Price",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {},
    {
     "rawSql": " SELECT \r\n    timestamp,\r\n    open,\r\n    symbol\r\n  FROM stock_data\r\n  WHERE symbol = '${symbols_list}';",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "Daily Biggest Gap and Volatility",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH \r\ndaily_data AS (\r\n  SELECT \r\n    timestamp,\r\n    first(open) AS open_price,\r\n    last(close) AS last_price,\r\n    symbol\r\n  FROM stock_data\r\n  WHERE symbol = '${symbols_list}'\r\n  SAMPLE BY 1d\r\n),\r\ndaily_with_prev AS (\r\n  SELECT\r\n    d.timestamp,\r\n    d.open_price,\r\n    d.last_price AS current_day_close,\r\n    prev.last_price AS previous_day_close_price,\r\n    d.open_price - prev.last_price AS open_vs_prev_close_diff, -- Daily gap\r\n    d.last_price - d.open_price AS intraday_change -- Intraday volatility\r\n  FROM daily_data d\r\n  LEFT JOIN daily_data prev \r\n    ON prev.timestamp = dateadd('d', -1, d.timestamp)\r\n  WHERE d.symbol = '${symbols_list}'\r\n)\r\nSELECT\r\n  MAX(ABS(open_vs_prev_close_diff)) AS Biggest_Daily_Gap,\r\n  AVG(ABS(intraday_change)) AS Average_Daily_Volatility,\r\n  timestamp\r\nFROM daily_with_prev\r\nWHERE previous_day_close_price IS NOT NULL\r\nGROUP BY timestamp;",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "Parametrizable Moving Average with Open Price",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    timestamp,\r\n    symbol,\r\n    open,\r\n    avg(open) OVER (\r\n        PARTITION BY symbol\r\n        ORDER BY timestamp\r\n        ROWS BETWEEN '${custom_average_interval_minutes}' PRECEDING AND CURRENT ROW\r\n    ) AS open_moving_avg\r\nFROM stock_data\r\nWHERE \r\n    open > 0 AND\r\n    symbol = '${symbols_list}';\r\n",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "Daily Average Return",
   "type": "gauge",
   "description": "How much value do we put at risk by investing in a particular stock?¶\nThere are many ways we can quantify risk, one of the most basic ways using the information we've gathered on daily percentage returns is by comparing the expected return with the standard deviation of the daily returns.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "WITH daily_returns AS (\r\n  SELECT\r\n    timestamp,\r\n    symbol,\r\n    ((last(close) - first(open)) / first(open)) * 100 AS daily_return_pct\r\n  FROM stock_data\r\n  WHERE symbol = '${symbols_list}'\r\n)\r\nSELECT\r\n  AVG(daily_return_pct) AS expected_return\r\n  --STDDEV_SAMP(daily_return_pct) AS volatility\r\nFROM daily_returns\r\nWHERE\r\n  symbol = '${symbols_list}';",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "Price Change from First Ingested Data",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "WITH first_last AS (\r\n  SELECT\r\n    first(close) AS start_price,\r\n    last(close) AS end_price\r\n  FROM stock_data\r\n  WHERE symbol = '${symbols_list}'\r\n)\r\nSELECT\r\n  ((end_price - start_price) / start_price) * 100 AS price_change_pct\r\nFROM first_last;",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "Sentiment Score Definitions",
   "type": "text",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 16 },
   "options": {
    "content": "**Sentiment Score Definition:**\n$sentiment_score_definition\n\n**Relevance Score Definition:**\n$relevance_score_definition\n"
   }
  },
  {
   "title": "Current Average Relevance and Sentiment Score ",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    ticker_sentiment->>'ticker' AS ticker,\r\n    AVG((ticker_sentiment->>'relevance_score')::float) AS avg_relevance_score,\r\n    AVG((ticker_sentiment->>'ticker_sentiment_score')::float) AS avg_sentiment_score\r\nFROM \r\n    sentiment_data,\r\n    jsonb_array_elements(content->'feed'->0->'ticker_sentiment') AS ticker_sentiment\r\nWHERE \r\n     ticker_sentiment->>'ticker' = '${symbols_list}'\r\nGROUP BY \r\n    ticker\r\nORDER BY \r\n    ticker;\r\n"
    }
   ]
  },
  {
   "title": "Best and Worst News by Sentiment Score",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "rawSql": "WITH sentiment_data_with_rank AS (\r\n    SELECT\r\n        content->>'items' AS items,\r\n        feed_item->>'title' AS title,\r\n        feed_item->>'url' AS url,\r\n        (ticker_sentiment->>'ticker_sentiment_score')::float AS sentiment_score,\r\n        (ticker_sentiment->>'relevance_score')::float AS relevance_score,\r\n        ROW_NUMBER() OVER (ORDER BY (ticker_sentiment->>'ticker_sentiment_score')::float DESC) AS best_rank,\r\n        ROW_NUMBER() OVER (ORDER BY (ticker_sentiment->>'ticker_sentiment_score')::float ASC) AS worst_rank\r\n    FROM\r\n        sentiment_data,\r\n        jsonb_array_elements(content->'feed') AS feed_item,\r\n        jsonb_array_elements(feed_item->'ticker_sentiment') AS ticker_sentiment\r\n)\r\nSELECT\r\n    title AS Title,\r\n    sentiment_score AS Sentiment_Score,\r\n    relevance_score AS Relevance_Score,\r\n    url AS URL,\r\n    CASE \r\n        WHEN best_rank = 1 THEN 'Positive'\r\n        WHEN worst_rank = 1 THEN 'Negative'\r\n    END AS Sentiment_Type\r\nFROM \r\n    sentiment_data_with_rank\r\nWHERE \r\n    best_rank = 1 OR worst_rank = 1\r\nORDER BY Sentiment_Type;\r\n"
    }
   ]
  }
 ]
}